-- CREATE TABLE students(
--  students_id SERIAL PRIMARY KEY,
--  first_name VARCHAR (50) NOT NULL,
--  last_name VARCHAR (50) NOT NULL,
--  birth_date date NOT NULL)

-- INSERT INTO students (first_name, last_name,birth_date)
-- VALUES ('Marc', 'Benichou', '1998-02-11'),
--   ('Yoan', 'Cohen', '2010-03-12'),
--   ('Lea', 'Benichou', '1987-07-27'),
--   ('Amelia', 'Dux', '1996-04-07'),
--   ('David', 'Grez', '2003-06-14'),
--   ('Omer', 'Simpson', '1980-10-03');

-- SELECT first_name, last_name FROM students
-- SELECT *FROM students where students_id=2
-- SELECT first_name,last_name FROM students WHERE last_name = 'Benichou'  AND 
-- first_name = 'Marc' ;
-- SELECT first_name, last_name FROM students WHERE last_name = 'Benichou' OR first_name = 'Marc';
-- SELECT *
-- FROM students
-- WHERE first_name LIKE '%a%';
-- SELECT *
-- FROM students
-- WHERE first_name LIKE 'a%';
-- SELECT *
-- FROM students
-- WHERE first_name LIKE '%a';
-- SELECT *
-- FROM students
-- WHERE SUBSTRING(first_name, LENGTH(first_name) - 1, 1) = 'a';
-- SELECT*FROM students limit 3
-- SELECT *
-- FROM students
-- WHERE birth_date >= '2000-01-01';
--  SELECT*FROM students